package heplers;

import java.util.HashMap;
import java.util.Map;

public class StaticConstants {

    public static Map<String, String> personOccupations = new HashMap() {{
        put("A197", "Navy Credit Union Trades");
        put("A198", "Army Credit Union Trades");
        put("A199", "Armed Forces");
        put("C120", "Police/Trooper");
        put("C121", "Mail/Postmaster");
        put("C122", "Mail Carrier/Postal");
        put("C123", "Judge/Referee");
        put("C124", "Firefighter");
        put("C125", "Court Reporter");
        put("C126", "Corrections/Probation/Parole");
        put("C127", "Civil Service/Government");
        put("C128", "Air Traffic Control");
        put("E793", "Vice President");
        put("E794", "Treasurer");
        put("E795", "President");
        put("E796", "Politician/Legislator/Diplomat");
        put("E797", "Comptroller");
        put("E798", "CEO/CFO/Chairman/Corp Officer");
        put("E799", "Executive/Upper Management");
        put("H326", "Social Worker/Case Worker");
        put("H327", "Nurse/LPN");
        put("H328", "Nurse (Registered)");
        put("H329", "Nurse");
        put("H330", "Therapists/Physical");
        put("H331", "Therapist");
        put("H332", "Technician/X-ray");
        put("H333", "Technician/Lab");
        put("H334", "Psychologist");
        put("H335", "Pharmacist/Pharmacy");
        put("H336", "Optometrist");
        put("H337", "Optician");
        put("H338", "Nurses Aide/Orderly");
        put("H339", "Medical/Paramedic");
        put("H340", "Medical Technician");
        put("H341", "Medical Secretary");
        put("H342", "Medical Assistant");
        put("H343", "Health Care");
        put("H344", "Dietician");
        put("H345", "Dentist");
        put("H346", "Dental Hygienist");
        put("H347", "Dental Assistant");
        put("H348", "Chiropractor");
        put("I143", "Trainer");
        put("I144", "Teacher");
        put("I145", "Professor");
        put("I146", "Lecturer");
        put("I147", "Instructor");
        put("I148", "Counselor");
        put("I149", "Coach");
        put("L394", "Welder");
        put("L395", "Waiter/Waitress");
        put("L396", "Utility");
        put("L397", "Upholstery");
        put("L398", "Typesetter");
        put("L399", "Transportation");
        put("L400", "Toolmaker");
        put("L401", "Sorter");
        put("L402", "Shipping/Import/Export/Custom");
        put("L403", "Sheet Metal Worker/Steel Worker");
        put("L404", "Setup man");
        put("L405", "Seamstress/Tailor/Handicraft");
        put("L406", "Sanitation/Exterminator");
        put("L407", "Roofer");
        put("L408", "Repairman");
        put("L409", "Production");
        put("L410", "Printer");
        put("L411", "Presser");
        put("L412", "Press Operator");
        put("L413", "Porter");
        put("L414", "Polisher");
        put("L415", "Plumber");
        put("L416", "Pipe fitter");
        put("L417", "Parts (Auto Etc.)");
        put("L418", "Painter");
        put("L419", "Packer");
        put("L420", "Operator/Machine Operator");
        put("L421", "Operator/Forklift Operator");
        put("L422", "Operator/Crane Operator");
        put("L423", "Operator/Boilermaker");
        put("L424", "Operator");
        put("L425", "Oil Industry/Driller");
        put("L426", "Mold Maker/Molder/Injection Mold");
        put("L427", "Miner");
        put("L428", "Millwright");
        put("L429", "Mill worker");
        put("L430", "Meter Reader");
        put("L431", "Mechanic");
        put("L432", "Material Handler");
        put("L433", "Mason/Brick/Etc.");
        put("L434", "Maintenance/Supervisor");
        put("L435", "Maintenance");
        put("L436", "Machinist");
        put("L437", "Locksmith");
        put("L438", "Loader");
        put("L439", "Lithographer");
        put("L440", "Lineman");
        put("L441", "Laborer");
        put("L442", "Journeyman");
        put("L443", "Janitor");
        put("L444", "Ironworker");
        put("L445", "Installer");
        put("L446", "Inspector");
        put("L447", "Housekeeper/Maid");
        put("L448", "Helper");
        put("L449", "Grocer");
        put("L450", "Grinder");
        put("L451", "Glazier");
        put("L452", "Gardener/Landscaper");
        put("L453", "Furrier");
        put("L454", "Foundry Worker");
        put("L455", "Forestry");
        put("L456", "Foreman/Shop Foreman");
        put("L457", "Foreman/Crew leader");
        put("L458", "Food Service");
        put("L459", "Fitter");
        put("L460", "Fisherman/Seaman");
        put("L461", "Finisher");
        put("L462", "Farmer/Dairyman");
        put("L463", "Factory Workman");
        put("L464", "Fabricator");
        put("L465", "Electrician");
        put("L466", "Driver/Truck Driver");
        put("L467", "Driver/Bus Driver");
        put("L468", "Driver");
        put("L469", "Dock Worker");
        put("L470", "Cutter");
        put("L471", "Custodian");
        put("L472", "Crewman");
        put("L473", "Courier/Delivery/Messenger");
        put("L474", "Cosmetologist");
        put("L475", "Cook");
        put("L476", "Construction");
        put("L477", "Conductor");
        put("L478", "Clerk/Stock");
        put("L479", "Clerk/Produce");
        put("L480", "Clerk/Deli");
        put("L481", "Cleaner/Laundry");
        put("L482", "Child Care/Day Care/Babysitter");
        put("L483", "Chef/Butler");
        put("L484", "Carpenter/Furniture/Woodworking");
        put("L485", "Butcher/Meat Cutter");
        put("L486", "Brewer");
        put("L487", "Brakeman");
        put("L488", "Bodyman");
        put("L489", "Binder");
        put("L490", "Bartender");
        put("L491", "Barber/Hairstylist/Beautician");
        put("L492", "Baker");
        put("L493", "Auto Mechanic");
        put("L494", "Attendant");
        put("L495", "Athlete/Professional");
        put("L496", "Assembler");
        put("L497", "Apprentice");
        put("L498", "Animal Technician/Groomer");
        put("M673", "Supervisor");
        put("M674", "Superintendent");
        put("M675", "Principal/Dean/Educator");
        put("M676", "Planner");
        put("M677", "Manager/Warehouse Manager");
        put("M678", "Manager/Traffic Manager");
        put("M679", "Manager/Store Manager");
        put("M680", "Manager/Sales Manager");
        put("M681", "Manager/Regional Manager");
        put("M682", "Manager/Property Manager");
        put("M683", "Manager/Project Manager");
        put("M684", "Manager/Product Manager");
        put("M685", "Manager/Plant Manager");
        put("M686", "Manager/Office Manager");
        put("M687", "Manager/Marketing Manager");
        put("M688", "Manger/General Manager");
        put("M689", "Manager/Division Manager");
        put("M690", "Manager/District Manager");
        put("M691", "Manager/Credit Manager");
        put("M692", "Manager/Branch Manager");
        put("M693", "Manager/Assistant Manager");
        put("M694", "Manager");
        put("M695", "Editor");
        put("M696", "Director/Executive Director");
        put("M697", "Director/Art Director");
        put("M698", "Account Executive");
        put("P244", "Volunteer");
        put("P245", "Student");
        put("P246", "Part Time");
        put("P247", "Retired/Pensioner");
        put("P249", "Homemaker");
        put("S295", "Data Entry/Key Punch");
        put("S296", "Typist");
        put("S297", "Secretary");
        put("S298", "Legal Secretary");
        put("S299", "Legal/Paralegal/Assistant");
        put("T896", "Computer/Systems Analyst");
        put("T897", "Computer Programmer");
        put("T898", "Computer Operator");
        put("T978", "Veterinarian");
        put("T979", "Statistician/Actuary");
        put("T980", "Scientist");
        put("T981", "Pilot");
        put("T982", "Pastor");
        put("T983", "Medical Doctor/Physician");
        put("T984", "Librarian/Archivist");
        put("T985", "Legal/Attorney/Lawyer");
        put("T987", "Geologist");
        put("T988", "Engineer/Mechanical");
        put("T989", "Engineer/Industrial");
        put("T990", "Engineer/Field");
        put("T991", "Engineer/Electrical/Electronic");
        put("T992", "Engineer/Civil");
        put("T993", "Engineer/Chemical");
        put("T994", "Engineer/Aerospace");
        put("T995", "Engineer");
        put("T996", "Curator");
        put("T997", "Chemist");
        put("T998", "Architect");
        put("W520", "Writer");
        put("W521", "Water Treatment");
        put("W522", "Ward Clerk");
        put("W523", "Union Member/Rep.");
        put("W524", "Travel Agent");
        put("W525", "Transcripter/Translator");
        put("W526", "Tester");
        put("W527", "Teller/Bank Teller");
        put("W528", "Telemarketer/Telephone/Operator");
        put("W529", "Technician");
        put("W530", "Surveyor");
        put("W531", "Security");
        put("W532", "Sales Clerk/Counterman");
        put("W533", "Sales");
        put("W534", "Researcher");
        put("W535", "Reporter");
        put("W536", "Receptionist");
        put("W537", "Real Estate/Realtor");
        put("W538", "Quality Control");
        put("W539", "Purchasing");
        put("W540", "Publishing");
        put("W541", "Public Relations");
        put("W542", "Photography");
        put("W543", "Personnel/Recruiter/Interviewer");
        put("W544", "Musician/Music/Dance");
        put("W545", "Model");
        put("W546", "Merchandiser");
        put("W547", "Marketing");
        put("W548", "Jeweler");
        put("W549", "Interior Designer");
        put("W550", "Insurance/Underwriter");
        put("W551", "Insurance/Agent");
        put("W552", "Hostess/Host/Usher");
        put("W553", "Graphic Designer/Commercial Artist");
        put("W554", "Florist");
        put("W555", "Flight Attendant/Steward");
        put("W556", "Finance");
        put("W557", "Expeditor");
        put("W558", "Estimator");
        put("W559", "Draftsman");
        put("W560", "Dispatcher");
        put("W561", "Detective/Investigator");
        put("W562", "Designer");
        put("W563", "Customer Service/Representative");
        put("W564", "Coordinator");
        put("W565", "Consultant/Advisor");
        put("W566", "Conservation/Environment");
        put("W567", "Communications");
        put("W568", "Collector");
        put("W569", "Clerk/File");
        put("W570", "Clerk");
        put("W571", "Claims Examiner/Rep/Adjudicator");
        put("W572", "Checker");
        put("W573", "Caterer");
        put("W574", "Cashier");
        put("W575", "Buyer");
        put("W576", "Broker/Stock/Trader");
        put("W577", "Broker");
        put("W578", "Bookkeeper");
        put("W579", "Banker/Loan Processor");
        put("W580", "Banker/Loan Office");
        put("W581", "Banker");
        put("W582", "Auditor");
        put("W583", "Auctioneer");
        put("W584", "Artist");
        put("W585", "Appraiser");
        put("W586", "Analyst");
        put("W587", "Aide/Assistant/Technical");
        put("W588", "Aide/Assistant/Staff");
        put("W589", "Aide/Assistant/School");
        put("W590", "Aide/Assistant/Office");
        put("W591", "Aide/Assistant/Executive");
        put("W592", "Aide/Assistant");
        put("W593", "Agent");
        put("W594", "Advertising");
        put("W595", "Administration/Management");
        put("W596", "Adjuster");
        put("W597", "Actor/Entertainer/Announcer");
        put("W598", "Accounting/Biller/Billing clerk");
    }};

}
